package Builder;

public class Director {

    public void constructLorenIpsum(IBuilder builder) {
        builder.setTitle("Loren Ipsum");
        builder.setAuthor("https://www.lipsum.com/");
        builder.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut aliquet erat sed purus "
                + "feugiat faucibus. Donec cursus volutpat tortor, a ultrices lacus hendrerit imperdiet. Sed "
                + "venenatis vehicula eleifend. Duis et ultricies tellus, eu volutpat quam. Mauris volutpat "
                + "dui at odio accumsan auctor. Maecenas porttitor consequat felis non maximus. Vivamus "
                + "tristique mattis imperdiet. Phasellus vitae dignissim neque. Curabitur nulla augue, "
                + "elementum id mollis sed, dapibus ac libero. Vivamus nec vestibulum eros. Maecenas quis "
                + "malesuada diam. Proin ullamcorper rhoncus elit vitae dapibus. Aenean enim orci, varius "
                + "ut tristique rhoncus, tempor a sapien.\n"
                + "Nam at ultricies sapien. Sed eget ex convallis, tincidunt orci vel, eleifend augue. "
                + "Suspendisse sodales faucibus varius. Lorem ipsum dolor sit amet, consectetur adipiscing "
                + "elit. Donec eget sapien felis. Suspendisse viverra arcu nec varius sollicitudin. Ut at"
                + " tempus ligula. Nulla venenatis, ante ut gravida tristique, nisl risus sagittis justo, "
                + "eu imperdiet risus enim non purus. Praesent et libero molestie, elementum sapien at, "
                + "sollicitudin elit. Donec ut nisl non magna dignissim dapibus sed sit amet ante. "
                + "Aenean ornare at ante quis porttitor. Suspendisse finibus, augue id maximus sollicitudin, "
                + "mi ipsum pulvinar urna, a gravida libero nisi ac mauris. Ut feugiat vestibulum lectus, "
                + "eu venenatis urna porttitor quis. Sed odio neque, porta in vehicula at, varius ac eros. "
                + "Etiam vitae porttitor eros. Aenean sed pretium urna, eu luctus diam.\n"
                + "Cras id velit eu elit volutpat feugiat. Donec porta venenatis purus, tincidunt lobortis "
                + "sem tempus vitae. Sed molestie convallis lorem, at imperdiet augue. Nullam neque ligula, "
                + "egestas nec tristique vel, pulvinar non est. Lorem ipsum dolor sit amet, consectetur "
                + "adipiscing elit. Ut vel lacinia eros. Aenean id pharetra risus, eu consectetur massa. "
                + "In id arcu urna. Sed pulvinar metus a nisl convallis lobortis. Curabitur facilisis dui "
                + "eu ligula convallis aliquet. Etiam fermentum magna sit amet sapien pellentesque, ac "
                + "vestibulum magna malesuada. Proin ac lorem at sem vestibulum euismod et aliquam lacus. "
                + "Quisque sit amet maximus sapien, at laoreet lorem. Donec pretium quam vitae eros "
                + "consequat, eu molestie purus accumsan. Vestibulum erat felis, interdum quis efficitur "
                + "a, finibus id purus.\n"
                + "Duis aliquet varius nisl ut luctus. Etiam scelerisque, sapien eu ultricies euismod, "
                + "nibh arcu porttitor massa, nec mattis nisl massa eu nunc. Sed ligula urna, sollicitudin "
                + "sed massa eget, posuere scelerisque ex. Donec magna ex, cursus et erat vitae, cursus "
                + "cursus elit. Fusce at augue quis justo ultrices feugiat sit amet sit amet sem. Quisque "
                + "nec magna quis orci convallis lobortis. Fusce facilisis lacus non sapien bibendum "
                + "interdum. Cras vel molestie mi. Vivamus porttitor tempus ipsum, tempor posuere dui "
                + "commodo sed. Ut vehicula placerat venenatis. Fusce tempus lacinia neque ac suscipit. "
                + "Fusce at tristique ipsum. Suspendisse mollis tellus vel eros fermentum, et porttitor "
                + "sem facilisis. Fusce nibh ante, mollis a mollis accumsan, ultricies varius erat. "
                + "Morbi sed mauris ultrices, tincidunt neque a, blandit dui. Suspendisse diam ante, "
                + "ullamcorper non volutpat eget, luctus fermentum enim.\n"
                + "Nulla ac metus ut libero tempus egestas. Vivamus consequat ipsum sed condimentum "
                + "eleifend. Aenean vitae urna at elit facilisis viverra. Phasellus eget dapibus mi. "
                + "Praesent ultricies nec nisl eu maximus. Maecenas egestas convallis vulputate. "
                + "Suspendisse iaculis sit amet lacus quis rhoncus. Fusce quis lectus suscipit ante "
                + "maximus congue ac nec turpis. Vivamus tincidunt eget tortor ut ultrices. Nam massa "
                + "ligula, porta sed pellentesque mollis, accumsan in neque. Donec mollis tincidunt velit "
                + "eu egestas. Curabitur quis turpis at lorem gravida porta vel in sem. Sed vel "
                + "hendrerit arcu. Etiam sed neque a nibh condimentum pharetra non sit amet justo.");
    }
}
